apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lencr-issuer
spec:
  acme:
    server: {{ .Values.lencr.endpoint.url }}
    privateKeySecretRef:
      name: lencr-issuer-account-key
    solvers:
    - http01:
        ingress:
          ingressClassName: {{ .Values.lencr.solver.ingressClassName }}