apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: step-issuer
  labels:
    app.kubernetes.io/name: step-integration
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}    
    app.kubernetes.io/component: hcp-vault-secret
spec:
  hcpAuthRef: hcp-auth
  appName: step-issuer
  destination:
    create: true
    name: step-issuer-secret
  refreshAfter: {{ .Values.hcp.refreshAfter }}