apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPAuth
metadata:
  name: hcp-auth
  labels:
    app.kubernetes.io/name: step-integration
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: hcp-vault-secret
spec:
  organizationID: {{ .Values.hcp.organizationId }}
  projectID: {{ .Values.hcp.projectId }} 
  servicePrincipal:
    secretRef: {{ .Values.hcp.principal.secretRef }}