apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: step-issuer
spec:
  hcpAuthRef: hcp-auth
  appName: step-issuer
  destination:
    create: true
    name: step-issuer-secret
  refreshAfter: 1h