apiVersion: certmanager.step.sm/v1beta1
kind: StepClusterIssuer
metadata:
  name: step-issuer
  labels:
    app.kubernetes.io/name: step-integration
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}    
    app.kubernetes.io/component: cert-manager
spec:
  # The CA URL:
  url: {{ .Values.step.authority.url }}
  # The base64 encoded version of the CA root certificate in PEM format:
  caBundle: {{ .Values.step.authority.caBundle }}
  # The provisioner name, kid, and a reference to the provisioner password secret:
  provisioner:
    name: {{ .Values.step.authority.provisioner.name }}
    kid: {{ .Values.step.authority.provisioner.kid }}
    passwordRef:
      name: step-issuer-secret
      namespace: {{ .Release.Namespace }}
      key: password

